name: MOTDBroadcaster
version: 1.00
main: me.ash.MOTDBroadcast.MOTDBroadcast

commands:

  motd:
    description: displays motd
    usage: |
      /motd
    permission: motd.motdbroadcaster

  setmotd:
    description: Sets a new motd
    usage: |
      /setmotd [motd]
    permission: setMOTD.motdbroadcaster

  broadcast:
    description: Broadcast to all players
    usage: |
      /broadcast [message]
    permission: broadcast.motdbroadcaster

permissions:

  motd.motdbroadcaster:
    description: Display motd

  setMOTD.motdbroadcaster:
    description: Set motd

  broadcast.motdbroadcaster:
    description: Broadcast a message